import type { Spot } from '@/types/spot';

export const mockSpots: Spot[] = [
  {
    id: 'spot-1',
    name: '梧桐树下咖啡',
    source: 'system',
    spotType: 'cafe',
    district: '徐汇区',
    addressHint: '近安福路口，梧桐街角旁',
    lat: 31.2206,
    lng: 121.4458,
    tags: ['咖啡', '宠物友好', '室外座位'],
    description: '安静街角小店，门口和靠窗区域对带宠物停留比较友好。',
    votes: 128,
    petFriendlyLevel: 'high',
    priceLevel: '$$',
    businessHours: '08:30 - 21:30',
    verified: true,
    merchantStatus: 'claimed',
  },
  {
    id: 'spot-2',
    name: '滨江散步带',
    source: 'system',
    spotType: 'park',
    district: '浦东新区',
    addressHint: '滨江步道旁，近陆家嘴江边段',
    lat: 31.2338,
    lng: 121.4991,
    tags: ['散步', '江边', '开阔空间'],
    description: '适合早晚遛宠，视野开阔，步道宽，周末人流相对较多。',
    votes: 204,
    petFriendlyLevel: 'high',
  },
  {
    id: 'spot-3',
    name: '静安口袋公园',
    source: 'system',
    spotType: 'park',
    district: '静安区',
    addressHint: '地铁静安寺站步行可达',
    lat: 31.2282,
    lng: 121.4484,
    tags: ['公园', '休息', '绿地'],
    description: '小型绿地空间，周边社区氛围轻松，适合短暂停留和散步。',
    votes: 96,
    petFriendlyLevel: 'medium',
  },
  {
    id: 'spot-4',
    name: '安福路宠物面包房',
    source: 'system',
    spotType: 'store',
    district: '徐汇区',
    addressHint: '近武康路，街区步行氛围轻松',
    lat: 31.2109,
    lng: 121.4442,
    tags: ['面包', '宠物友好', '街区'],
    description: '店员对宠物比较友善，门前适合短暂停靠，周边街区也方便步行。',
    votes: 173,
    petFriendlyLevel: 'high',
    priceLevel: '$$',
    businessHours: '10:00 - 20:00',
    verified: true,
    merchantStatus: 'claimed',
  },
  {
    id: 'spot-5',
    name: '虹桥城市草坪',
    source: 'system',
    spotType: 'park',
    district: '长宁区',
    addressHint: '近虹桥路地铁站，开放草坪一侧',
    lat: 31.1997,
    lng: 121.317,
    tags: ['草坪', '奔跑', '户外'],
    description: '草地面积较大，适合放松活动，但高峰时段需要注意周边人流。',
    votes: 147,
    petFriendlyLevel: 'medium',
  },
  {
    id: 'spot-6',
    name: '愚园路社区书店',
    source: 'system',
    spotType: 'indoor',
    district: '长宁区',
    addressHint: '愚园路沿街，近社区转角口',
    lat: 31.2231,
    lng: 121.4305,
    tags: ['书店', '安静', '社区'],
    description: '书店外侧休息区允许短时间带宠停留，整体环境安静整洁。',
    votes: 88,
    petFriendlyLevel: 'low',
    businessHours: '10:00 - 22:00',
  },
];
